name: Doc

on:
  push:
    paths:
      - 'doc/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Artifact Directory
      run: |
        mkdir ./artifact
    - name: Aglio
      uses: docker://humangeo/aglio
      with:
        args: -i doc/api.md -o ./artifact/api.html
    - uses: actions/upload-artifact@master
      with:
        name: API HTML
        path: ./artifact
